// Generated by CoffeeScript 1.9.3
(function() {
  var App, Arrows, ListingCell, ListingHeading, ListingRow, ListingsTable;

  App = React.createClass({
    getInitialState: function() {
      return {
        headings: ['_id', 'type', 'title', 'price', 'region', 'location', 'hasPic', 'date', 'id'],
        listings: [],
        page: 0
      };
    },
    getListings: function(page) {
      var tableData;
      tableData = {
        page: page,
        pageSize: 15
      };
      return $.get('listings.json', tableData, (function(listings) {
        this.setState({
          listings: listings,
          page: page
        });
      }).bind(this));
    },
    componentDidMount: function() {
      return this.getListings(this.state.page);
    },
    handleClick: function(direction) {
      if (direction === 'Next') {
        this.getListings(this.state.page + 1);
      } else if (direction === 'Previous' && this.state.page > 0) {
        this.getListings(this.state.page - 1);
      }
    },
    render: function() {
      return React.createElement("div", {
        "className": 'app'
      }, React.createElement("h1", null, "OneRent Listings"), React.createElement(ListingsTable, {
        "listings": this.state.listings,
        "headings": this.state.headings
      }), React.createElement(Arrows, {
        "onClickEvent": this.handleClick,
        "page": this.state.page
      }));
    }
  });

  ListingsTable = React.createClass({
    render: function() {
      var tableHeadings, tableRows;
      tableHeadings = this.props.headings.map(function(heading) {
        return React.createElement(ListingHeading, null, heading);
      });
      tableRows = this.props.listings.map((function(listing) {
        return React.createElement(ListingRow, {
          "headings": this.props.headings
        }, listing);
      }).bind(this));
      return React.createElement("table", {
        "id": 'listings',
        "className": "tablesorter"
      }, React.createElement("thead", null, React.createElement("tr", null, tableHeadings)), React.createElement("tbody", null, tableRows));
    }
  });

  ListingHeading = React.createClass({
    render: function() {
      return React.createElement("th", null, this.props.children);
    }
  });

  ListingRow = React.createClass({
    render: function() {
      var tableCells;
      tableCells = this.props.headings.map((function(heading) {
        return React.createElement(ListingCell, null, this.props.children[heading]);
      }).bind(this));
      return React.createElement("tr", null, tableCells);
    }
  });

  ListingCell = React.createClass({
    render: function() {
      return React.createElement("td", null, this.props.children);
    }
  });

  Arrows = React.createClass({
    handleClick: function(e) {
      return this.props.onClickEvent(e.target.value);
    },
    render: function() {
      return React.createElement("div", {
        "className": 'buttons'
      }, React.createElement("input", {
        "type": 'button',
        "value": 'Previous',
        "onClick": this.handleClick
      }), React.createElement("input", {
        "type": 'button',
        "value": 'Next',
        "onClick": this.handleClick
      }), this.props.page);
    }
  });

  React.render(React.createElement(App, null), document.getElementById('Container'));

}).call(this);
